// Generated by CoffeeScript 1.3.3
var Client, Gearman, GearmanDriver, url;

url = require('url');

Gearman = require('node-gearman');

Client = void 0;

GearmanDriver = (function() {

  function GearmanDriver() {}

  GearmanDriver.connect = function(server, done) {
    url = url.parse(server);
    Client = new Gearman(url.hostname, url.port);
    Client.on('connect', function() {
      return done();
    });
    return Client.connect();
  };

  GearmanDriver.disconnect = function(done) {
    Client.disconnect();
    return done();
  };

  GearmanDriver.register = function(name, handler) {
    return Client.registerWorker(name, function(payload, worker) {
      return handler(payload.toString('utf-8'), worker);
    });
  };

  GearmanDriver.submit = function(name, params) {
    return Client.submitJob(name, params);
  };

  return GearmanDriver;

})();

module.exports = GearmanDriver;
